services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-alpine
    ports:
      - 1984:1984
    environment:
      - DB_BACKEND=postgres
      - DB_PATH=postgresql://postgres:dbpass@db:5432/dbname
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
    ports:
      - "8084:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: