services:
  backend:
    build:
      dockerfile: dev.dockerfile
      context: .
    image: dev-backend
    ports:
      - "1984:1984"
      - "1985:1985"
    volumes:
      - ./backend:/backend
    environment:
      HOST: "0.0.0.0"
      PORT: 1984
      PP2P: 1985
    networks:
      - app-network
  frontend:
    build:
      dockerfile: dev.dockerfile
      context: ./frontend/remix/
    image: dev-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/remix:/frontend
    networks:
      - app-network
  localai:
    image: quay.io/go-skynet/local-ai:master-ffmpeg-core
    ports:
      - 8080:8080
    environment:
      MODELS_PATH: /models
      LLAMACPP_PARALLEL: 10
    volumes:
      - ./models:/models:cached
    networks:
      - app-network
    command:
      - meta-llama-3.1-8b-instruct
      - whisper-medium-q5_0

networks:
  app-network:
    driver: bridge
