{{- if and .Values.backend.sqlite.persistence.enabled (not .Values.backend.sqlite.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-sqlite-data
  namespace: {{ .Values.rootNamespace }}
spec:
  accessModes:
    - {{ .Values.backend.sqlite.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.sqlite.persistence.size }}
  {{- with .Values.backend.sqlite.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
