#!/bin/bash

set -e  # Exit on any error

# Parse command line arguments
FRONTEND=true
for arg in "$@"; do
    case $arg in
        --no-frontend)
            FRONTEND=false
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo "Options:"
            echo "  --no-frontend        Skip frontend build (useful for backend-only builds)"
            echo "  -h, --help           Show this help message"
            echo ""
            echo "Environment Variables for Build-time Defaults:"
            echo "  BUILD_DEFAULT_BOT                    Default bot credentials (format: username:password)"
            echo ""
            echo "Examples:"
            echo "  $0                                    # Build with frontend (default)"
            echo "  $0 --no-frontend                     # Build backend only (skip frontend)"
            echo "  BUILD_DEFAULT_BOT=mybot:mypass $0    # Build with custom bot credentials"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the repo root (parent of backend directory)
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

echo "Starting full build process..."
echo "Script directory: $SCRIPT_DIR"
echo "Repo root: $REPO_ROOT"
if [ "$FRONTEND" = false ]; then
    echo "Frontend build: Skipped (--no-frontend flag)"
fi

# Change to repo root
cd "$REPO_ROOT"

# Step 1: Build the static frontend (if not skipped)
if [ "$FRONTEND" = true ]; then
    echo "Step 1: Building static frontend..."
    ./development/scripts/build_static_frontend.sh
else
    echo "Step 1: Skipping frontend build (--no-frontend flag)"
fi

# Step 2: Increment minor version in metrics handler
if [ "$FRONTEND" = true ]; then
    echo "Step 2: Incrementing version in metrics handler..."
else
    echo "Step 1: Incrementing version in metrics handler..."
fi

BUMP_SCRIPT="./development/scripts/bump_backend_version.sh"
if [ -x "$BUMP_SCRIPT" ]; then
    "$BUMP_SCRIPT"
elif [ -f "$BUMP_SCRIPT" ]; then
    bash "$BUMP_SCRIPT"
else
    echo "Warning: $BUMP_SCRIPT not found; bumping backend version inline."
    VERSION_FILE="backend/api/metrics/handler.go"
    CURRENT_VERSION=$(grep 'var VERSION =' "$VERSION_FILE" | sed 's/.*"\(.*\)".*/\1/')
    IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
    if [ -z "$MAJOR" ] || [ -z "$MINOR" ] || [ -z "$PATCH" ]; then
        echo "Error: unexpected version format '$CURRENT_VERSION' in $VERSION_FILE"
        exit 1
    fi
    if ! [[ "$PATCH" =~ ^[0-9]+$ ]]; then
        echo "Error: patch segment is not numeric in version '$CURRENT_VERSION'"
        exit 1
    fi
    NEW_PATCH=$((PATCH + 1))
    NEW_VERSION_INLINE="${MAJOR}.${MINOR}.${NEW_PATCH}"
    TMP_FILE=$(mktemp)
    sed "s|var VERSION = \"${CURRENT_VERSION}\"|var VERSION = \"${NEW_VERSION_INLINE}\"|" "$VERSION_FILE" > "$TMP_FILE"
    mv "$TMP_FILE" "$VERSION_FILE"
    echo "Current version: $CURRENT_VERSION"
    echo "New version: $NEW_VERSION_INLINE"
fi
NEW_VERSION=$(grep 'var VERSION =' backend/api/metrics/handler.go | sed 's/.*"\(.*\)".*/\1/')
echo "Version updated to: $NEW_VERSION"

# Step 3: Generate Swagger documentation
if [ "$FRONTEND" = true ]; then
    echo "Step 3: Generating Swagger documentation..."
else
    echo "Step 2: Generating Swagger documentation..."
fi
cd backend

# Resolve the integration profile into a Go workspace. `prepare` materializes
# any missing checkouts (a no-op when they are already present, e.g. in the
# Docker build context), then regenerates backend/go.work,
# backend/integrations/externalintegrations/imports_gen.go and
# backend/.generated/build_tags from integrations.yaml.
#
# Set OPENCHAT_SKIP_INTEGRATION_PREPARE=1 when the workspace was already
# generated by an outer build (e.g. a nested sandbox container that does not
# ship PyYAML) and the checkouts are mounted read-only.
INTEGRATION_PROFILE="${INTEGRATION_PROFILE:-}"
if [ "${OPENCHAT_SKIP_INTEGRATION_PREPARE:-0}" = "1" ]; then
  echo "Skipping integration prepare (OPENCHAT_SKIP_INTEGRATION_PREPARE=1); using pre-generated workspace"
else
  echo "Preparing integrations (profile=${INTEGRATION_PROFILE:-manifest default})..."
  PYTHONPATH="$REPO_ROOT/development/integrations" \
    python3 -m openchat_integrations prepare ${INTEGRATION_PROFILE:+--profile "$INTEGRATION_PROFILE"}
fi

# IMPORTANT: This script is used in CI with GOOS/GOARCH set for cross-compilation.
# Build-time tools (like `swag`) must be built for the *host* platform so they
# can run locally. Capture the host platform before overriding.
HOST_GOOS="$(go env GOHOSTOS)"
HOST_GOARCH="$(go env GOHOSTARCH)"

# Build in Go workspace mode; the workspace selects the profile's modules and
# replaces all msgmate module paths, so go.mod no longer hardcodes integrations.
export GOWORK="$PWD/go.work"

BUILD_TAGS_FILE="$PWD/.generated/build_tags"
GO_TAGS=""
if [ -f "$BUILD_TAGS_FILE" ]; then
  GO_TAGS="$(cat "$BUILD_TAGS_FILE")"
fi
if [ -n "$GO_TAGS" ]; then
  export GOFLAGS="${GOFLAGS:+$GOFLAGS }-tags=${GO_TAGS}"
fi

echo "Using GOWORK=${GOWORK} GOFLAGS=${GOFLAGS:-<unset>}"

echo "Downloading module dependencies..."
# Network hiccups (eg module proxy stream errors mid-download) can abort the
# module fetch after minutes of transfer; retry instead of failing the build.
mod_attempts=0
until go mod download; do
  mod_attempts=$((mod_attempts + 1))
  if [ "$mod_attempts" -ge 3 ]; then
    echo "go mod download failed after ${mod_attempts} attempts" >&2
    exit 1
  fi
  echo "go mod download failed (attempt ${mod_attempts}/3); retrying in 15s..." >&2
  sleep 15
done

# Build-time tools (like `swag`) must be installed for the *host* platform so they can run.
TARGET_GOOS="${GOOS:-}"
TARGET_GOARCH="${GOARCH:-}"

# Install swag tool if not already installed (install into a repo-local bin dir)
TOOLS_BIN="$PWD/.tools/bin"
mkdir -p "$TOOLS_BIN"
export PATH="$TOOLS_BIN:$PATH"
SWAG_PATH="$TOOLS_BIN/swag"

# Check if swag exists and is actually executable (not just present in PATH)
SWAG_WORKS=false
if [ -f "$SWAG_PATH" ]; then
    if "$SWAG_PATH" --version &> /dev/null; then
        SWAG_WORKS=true
    else
        echo "Existing swag binary is not executable, removing..."
        rm -f "$SWAG_PATH"
    fi
fi

if [ "$SWAG_WORKS" = false ]; then
    echo "Installing swag tool for host platform (${HOST_GOOS}/${HOST_GOARCH})..."
    CGO_ENABLED=0 GOBIN="$TOOLS_BIN" GOOS="$HOST_GOOS" GOARCH="$HOST_GOARCH" go install github.com/swaggo/swag/v2/cmd/swag@latest
fi

if [ ! -f "$SWAG_PATH" ]; then
    echo "Error: swag tool not found after installation at: $SWAG_PATH"
    exit 1
fi

# Generate swagger documentation
echo "Generating swagger.json..."
$SWAG_PATH init --parseDependency --parseDependencyLevel 3 --parseInternal --output ./docs --generalInfo ./main.go

# Copy swagger files to server directory for embedding
echo "Copying swagger files for embedding..."
cp ./docs/swagger.json ./server/

# Step 4: Build the Go backend
if [ "$FRONTEND" = true ]; then
    echo "Step 4: Building Go backend..."
else
    echo "Step 3: Building Go backend..."
fi

# Restore target platform env for the actual backend build (if they were set by the caller)
if [ -n "$TARGET_GOOS" ]; then export GOOS="$TARGET_GOOS"; else unset GOOS; fi
if [ -n "$TARGET_GOARCH" ]; then export GOARCH="$TARGET_GOARCH"; else unset GOARCH; fi

# Build ldflags for build-time defaults
LDFLAGS=""
TRIMPATH_FLAG=""

# Release builds strip symbol tables and record reproducible paths.
if [ "${OPEN_CHAT_RELEASE_BUILD:-0}" = "1" ]; then
    echo "Release build enabled (OPEN_CHAT_RELEASE_BUILD=1): adding -trimpath -s -w"
    TRIMPATH_FLAG="-trimpath"
    LDFLAGS="$LDFLAGS -s -w"
fi

# Add build-time defaults if environment variables are set
if [ -n "$BUILD_DEFAULT_BOT" ]; then
    LDFLAGS="$LDFLAGS -X backend/cmd.buildTimeDefaultBot=$BUILD_DEFAULT_BOT"
    echo "Setting build-time default bot: $BUILD_DEFAULT_BOT"
fi

# Build with ldflags
if [ -n "$LDFLAGS" ]; then
    echo "Building with ldflags: $LDFLAGS"
    go build $TRIMPATH_FLAG -ldflags "$LDFLAGS" -o backend .
else
    echo "Building backend (no custom ldflags)"
    go build $TRIMPATH_FLAG -o backend .
fi

echo "Full build complete!"
if [ "$FRONTEND" = true ]; then
    echo "Frontend built and copied to backend/frontend/"
else
    echo "Frontend build skipped (--no-frontend flag)"
fi
echo "Version updated to: $NEW_VERSION"
echo "Backend binary built as: backend"
