// Code generated by scripts/integrationdepsgen. DO NOT EDIT.

package externalintegrations

import (
	_ "github.com/msgmate-io/account-management-integration"
	_ "github.com/msgmate-io/admin-db-managemnt-integration"
	_ "github.com/msgmate-io/mcp-integration"
	_ "github.com/msgmate-io/rest-api-tool-integration"
	_ "github.com/msgmate-io/ssh-integration"
)
