// Code generated by scripts/integrationdepsgen. DO NOT EDIT.

package externalintegrations

import (
	_ "github.com/msgmate-io/docker-sandbox-integration"
	_ "github.com/msgmate-io/git-integration"
	_ "github.com/msgmate-io/go-client-integration"
	_ "github.com/msgmate-io/kubernetes-integration"
	_ "github.com/msgmate-io/matrix-integration"
	_ "github.com/msgmate-io/mcp-integration"
	_ "github.com/msgmate-io/rest-api-tool-integration"
)
