import type { Metadata } from "next";
import "./globals.css";
import { useThemeStore } from "@/components/ThemeToggle";
import { redirect } from 'next/navigation'
import { Layout } from "@/components/Layout";
import { headers, cookies } from "next/headers";

const PUBLIC_ROUTES = ["/"]
// session_id


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const heads = await headers() 
  const cookieStore = await cookies()
  const pathName = heads.get("x-pathname") || ""
  const sessionIdPresent = cookieStore.get("session_id")
  const isPublicRoute = PUBLIC_ROUTES.includes(pathName)
  
  if(isPublicRoute && sessionIdPresent){
    redirect("/chat")
  }

  return (
    <Layout>
        {children}
    </Layout>
  );
}
