import type { Metadata } from "next";
import "./globals.css";
import { useThemeStore } from "@/components/ThemeToggle";
import { Layout } from "@/components/Layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <Layout>
        {children}
    </Layout>
  );
}
