package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type dependency struct {
	Module     string `json:"module"`
	Version    string `json:"version"`
	ImportPath string `json:"import"`
}

type manifest struct {
	Dependencies []dependency `json:"dependencies"`
}

func main() {
	manifestPath := flag.String("manifest", "./tooldeps.json", "Path to tool dependency manifest")
	outputPath := flag.String("output", "./api/msgmate/externaltools/imports_gen.go", "Path to generated side-effect import file")
	syncDeps := flag.Bool("sync", true, "Download and add dependencies from manifest")
	flag.Parse()

	m, err := loadManifest(*manifestPath)
	if err != nil {
		fatalf("failed to load manifest: %v", err)
	}

	if *syncDeps {
		if err := syncDependencies(m.Dependencies); err != nil {
			fatalf("failed syncing dependencies: %v", err)
		}
	}

	if err := writeGeneratedImports(*outputPath, m.Dependencies); err != nil {
		fatalf("failed writing generated imports: %v", err)
	}
}

func loadManifest(path string) (manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return manifest{}, err
	}

	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return manifest{}, err
	}

	for i, dep := range m.Dependencies {
		dep.ImportPath = strings.TrimSpace(dep.ImportPath)
		dep.Module = strings.TrimSpace(dep.Module)
		dep.Version = strings.TrimSpace(dep.Version)

		if dep.ImportPath == "" {
			return manifest{}, fmt.Errorf("dependencies[%d] is missing import", i)
		}
		if strings.Contains(dep.ImportPath, "@") {
			return manifest{}, fmt.Errorf("dependencies[%d].import must not include @version", i)
		}
		if dep.Version != "" && strings.Contains(dep.Version, "@") {
			return manifest{}, fmt.Errorf("dependencies[%d].version must not include @", i)
		}

		m.Dependencies[i] = dep
	}

	return m, nil
}

func syncDependencies(deps []dependency) error {
	for _, dep := range deps {
		importTarget := dep.ImportPath
		if dep.Version != "" {
			importTarget += "@" + dep.Version
		}

		if err := runGoCommand("get", importTarget); err != nil {
			return fmt.Errorf("go get %s: %w", importTarget, err)
		}

		if dep.Module != "" {
			moduleTarget := dep.Module
			if dep.Version != "" {
				moduleTarget += "@" + dep.Version
			}
			if err := runGoCommand("mod", "download", moduleTarget); err != nil {
				return fmt.Errorf("go mod download %s: %w", moduleTarget, err)
			}
		}
	}

	return nil
}

func runGoCommand(args ...string) error {
	cmd := exec.Command("go", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func writeGeneratedImports(path string, deps []dependency) error {
	importSet := map[string]struct{}{}
	for _, dep := range deps {
		importSet[dep.ImportPath] = struct{}{}
	}

	imports := make([]string, 0, len(importSet))
	for importPath := range importSet {
		imports = append(imports, importPath)
	}
	sort.Strings(imports)

	var src bytes.Buffer
	src.WriteString("// Code generated by scripts/tooldepsgen. DO NOT EDIT.\n\n")
	src.WriteString("package externaltools\n\n")
	if len(imports) > 0 {
		src.WriteString("import (\n")
		for _, importPath := range imports {
			src.WriteString("\t_ \"")
			src.WriteString(importPath)
			src.WriteString("\"\n")
		}
		src.WriteString(")\n")
	}

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	return os.WriteFile(path, formatted, 0o644)
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
