basePath: /api/
host: beta.msgmate.io
info:
  contact: {}
  description: Hello there :)
  termsOfService: http://swagger.io/terms/
  title: Open-Chat 2.0 API
  version: "3.1"
paths:
  /user/self/:
    get:
      responses: {}
      summary: Show a bottle
swagger: "2.0"
