basePath: /
host: localhost:3000
info:
  contact: {}
  description: Hello there :)
  termsOfService: http://swagger.io/terms/
  title: Open-Chat 2.0 API
  version: "3.1"
paths:
  /api/user/login/:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: Login a user
  /api/user/self/:
    get:
      responses: {}
      summary: Show a bottle
swagger: "2.0"
