rootNamespace: default

registryAuth:
  use: false
  host: ghcr.io
  token: ""
  secretName: dockerconfigjson-github-com

backend:
  replicas: 1
  imageURL: ghcr.io/example/msgmate-open-chat:latest
  imagePullPolicy: IfNotPresent
  service:
    port: 1984
  sqlite:
    path: data.db
    persistence:
      enabled: false
      mountPath: /backend/data
      fileName: data.db
      size: 1Gi
      accessMode: ReadWriteOnce
      # storageClassName: ""
      # existingClaim: ""
  env:
    HOST: ""
    PORT: "1984"
    DB_BACKEND: sqlite
    DEBUG: "false"
    START_BOT: "false"
    ROOT_CREDENTIALS: "admin:random"

ingress:
  use: false
  className: public
  certManager: false
  host: ""
  extraAnnotations: {}
