namespace: default
registry:
  use: false
  host: "ghcr.io"
  authToken: "token"
certmanager:
  use: false
  name: letsencrypt-prod
ingress:
  use: true
  host: localhost
backend:
  replicas: 2
  imageURL: localhost:32000/open-chat-go-backend:latest
  registry:
    authRequired: false
    secretName: dockerconfigjson-github-com
  env:
    DEEPINFRA_API_KEY: ${DEEPINFRA_API_KEY}
    OPENAI_API_KEY: ${OPENAI_API_KEY}
postgresql:
  use: false
  auth:
    username: "admin"
    password: "password"
    database: "openchat"
mixtral:
  use: false
multibot:
  use: false